medication/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from . import api
from . import views

router = routers.DefaultRouter()
router.register(r'medication', api.MedicationViewSet)
router.register(r'MyDawa', api.myDawaModelSet)
router.register(r'MyDawaPrescriptions', api.myDawaPrescriptionsModelSet)

urlpatterns = (
    # urls for Django Rest Framework API
    url(r'^api/v1/', include(router.urls)),
    #url(r'^api/v2/', include(router.urls)),
)

urlpatterns += (
    # urls for models
    url(r'^medication/$', views.MedicationListView.as_view(), name='medication_models_list'),
    url(r'^prescription-pdf/$', views.PrescriptionPdf.as_view(), name='medication_prescription_pdf'),
    url(r'^search/$', views.MedicationSearchView.as_view(), name='medication_models_search'),
    url(r'^medication/new/(?P<patient_no>\S+)/$', views.MedicationCreateView.as_view(), name='medication_models_create'),
    url(r'^medication/detail/(?P<slug>\S+)/$', views.MedicationDetailView.as_view(), name='medication_models_detail'),
    url(r'^medication/update/(?P<slug>\S+)/$', views.MedicationUpdateView.as_view(), name='medication_models_update'),
)

nurse/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from . import api
from . import views

router = routers.DefaultRouter()
router.register(r'nurse', api.modelsViewSet)


urlpatterns = (
    # urls for Django Rest Framework API
    url(r'^api/v1/', include(router.urls)),
)

urlpatterns += (
    # urls for models
    # url(r'^nurse/list/$', views.ModelsListView.as_view(), name='nurse_triage_list'),
    url(r'^nurse/', views.NurseLandingView.as_view(), name='nurse_landing'),
    url(r'^create/(?P<patient_no>\S+)/$', views.NurseCreateView.as_view(), name='nurse_triage_create'),
    url(r'^nurse/detail/(?P<slug>\S+)/$', views.NurseDetailView.as_view(), name='nurse_triage_detail'),
    url(r'^nurse/update/(?P<slug>\S+)/$', views.NurseUpdateView.as_view(), name='nurse_triage_update'),
)

valentisHealth/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from account.views import Home
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = 'ValentisHealth Administration'
admin.site.site_title = 'ValentisHealth Administration'

urlpatterns = [
                  url(r'^tunnel/', admin.site.urls),
                  url(r'^registration/', include('registration.urls')),
                  url(r'^nurse/', include('nurse.urls')),
                  url(r'^medication/', include('medication.urls')),
                  url(r'^tests/', include('tests.urls')),
                  url(r'^clinic/', include('clinic.urls')),
                  url(r'^payments/', include('payments.urls')),
                  url(r'^account/', include('account.urls')),
                  url(r'^workflow/', include('workflow.urls')),
                  url(r'^$', include('registration.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

medication/models.py
from django.core.urlresolvers import reverse
from django_extensions.db.fields import AutoSlugField
from django.db.models import *
from django.conf import settings
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth import get_user_model
from django.contrib.auth import models as auth_models
from django.db import models as models
from django_extensions.db import fields as extension_fields
import uuid

class MyDawa(models.Model):
    brand = models.CharField(max_length=255)
    size = models.CharField(max_length=300)
    price = models.CharField(max_length=300)

    class Meta:
        ordering = ('brand',)

    def __str__(self):
        return self.brand + " : " + self.size + ":" + self.price


class Medication(models.Model):

    # Fields
    slug = extension_fields.AutoSlugField(populate_from='patient_no', blank=True)
    created = models.DateTimeField(auto_now_add=True, editable=False)
    last_updated = models.DateTimeField(auto_now=True, editable=False)
    prescription_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    triage_id = models.CharField(max_length=255, blank=True)
    email = models.CharField(max_length=50, blank=True)
    patient_no = models.CharField(max_length=30)
    patient_name = models.TextField(max_length=100)
    address = models.TextField(max_length=100)
    physical_address = models.TextField(max_length=100, blank=True)
    phone_number = models.CharField(max_length=30)
    signature = models.BinaryField(null=True, blank=True)
    prescription = models.TextField(max_length=400)



    class Meta:
        ordering = ('last_updated',)

    def __unicode__(self):
        return u'%s' % self.slug

    def get_absolute_url(self):
        return reverse('medication_models_detail', args=(self.slug,))

    def get_update_url(self):
       return reverse('medication_models_update', args=(self.slug,))

medication/forms.py
from django import forms
from .models import Medication


class MedicationForm(forms.ModelForm):
    class Meta:
        model = Medication
        fields = ['patient_no', 'patient_name', 'address', 'phone_number', 'prescription','physical_address']

medication/views.py
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render
from django.views.generic import DetailView, ListView, UpdateView, CreateView, View
from registration.models import Patient
from valentisHealth.authenticator import *
from .forms import MedicationForm
from .models import Medication
from valentisHealth.authenticator import *
from django.contrib.auth.mixins import UserPassesTestMixin

class MedicationListView(ListView):
    model = Medication


class MedicationCreateView(UserPassesTestMixin, CreateView):
    model = Medication
    form_class = MedicationForm

    def test_func(self):
        return is_nurse(self.request) or is_doctor(self.request) or is_callcenter(request)

    def form_valid(self, form):
        instance = form.save(commit=False)
        # status 4 means patient's in lab
        instance.status = 0
        try:
            patient_object = Patient.objects.get(patient_no=self.kwargs['patient_no'])
            instance.triage_id = patient_object.session_id
        except:
            pass
        instance.save()

        # try:
        #     visit = patientVisit.objects.get(patient_no=self.kwargs['patient_no']).latest('created')
        #     prescr = models.objects.get(triage_id=self.kwargs['patient_no']).latest('created')
        #     visit.prescription_id = prescr.presscription_id
        # except:
        #     pass

        return HttpResponseRedirect("/medication/search")

    def get_context_data(self, **kwargs):
        context = super(MedicationCreateView, self).get_context_data(**kwargs)

        try:
            patient_object = Patient.objects.get(patient_no=self.kwargs['patient_no'])
            patient_object.patient_name = patient_object.first_name + " " + patient_object.last_name
            context['patient'] = patient_object

        except:
            raise Http404('Requested user not found.')

        return context


class MedicationDetailView(UserPassesTestMixin, DetailView):
    model = Medication

    def test_func(self):
        return is_nurse(self.request) or is_doctor(self.request) or is_callcenter(request)



class MedicationUpdateView(UserPassesTestMixin, UpdateView):
    model = Medication
    form_class = Medication

    def test_func(self):
        return is_nurse(self.request) or is_doctor(self.request) or is_callcenter(request)


class MedicationSearchView(UserPassesTestMixin, View):
    model = Medication

    def test_func(self):
        return is_nurse(self.request) or is_doctor(self.request) or is_callcenter(request)

    # def get_template_names(self):
    #     return 'medication/medication_search.html'

    def get(self, request):

        return render(request, 'medication/medication_search.html')

class PrescriptionPdf(ListView):

    def test_func(self):
        return is_nurse(self.request) or is_doctor(self.request) or is_callcenter(request)

    # def get_template_names(self):
    #     return 'medication/medication_search.html'

    def get(self, request):
        return render(request, 'prescription_receipt.html')

medication/templates/medication/medication_detail.html
{% extends "base.html" %} {% load static %} {% block content %}
<script>
    $("#prescription_tab").addClass("current").siblings().removeClass("current")
</script>
<table class="table">
    <tr>
        <td>slug</td>
        <td>{{ object.slug }}</td>
    </tr>
    <tr>
        <td>created</td>
        <td>{{ object.created }}</td>
    </tr>
    <tr>
        <td>last_updated</td>
        <td>{{ object.last_updated }}</td>
    </tr>
    <tr>
        <td>prescription_id</td>
        <td>{{ object.prescription_id }}</td>
    </tr>
    <tr>
        <td>patient_no</td>
        <td>{{ object.patient_no }}</td>
    </tr>
    <tr>
        <td>patient_name</td>
        <td>{{ object.patient_name }}</td>
    </tr>
    <tr>
        <td>address</td>
        <td>{{ object.address }}</td>
    </tr>
    <tr>
        <td>phone_number</td>
        <td>{{ object.phone_number }}</td>
    </tr>
    <tr>
        <td>signature</td>
        <td>{{ object.signature }}</td>
    </tr>
    <tr>
        <td>prescription</td>
        <td>{{ object.prescription }}</td>
    </tr>
</table>
{% endblock %}

medication/templates/medication/medication_form.html
{% extends "base.html" %} {% load static %} {% load crispy_forms_tags %} {% block content %}
    <script>
        $("#prescription_tab").addClass("current").siblings().removeClass("current")
    </script>

    <script src="{% static 'js/bootbox.min.js' %}"></script>
    <script src="{% static 'js/fuse.min.js' %}"></script>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.bundle.min.js"
            integrity="sha384-feJI7QwhOS+hwpX2zkaeJQjeiwlhOP+SdQDqhgvvo1DsjtiSQByFdThsxO669S2D"
            crossorigin="anonymous"></script>

    <style>
        .divText {
            padding: 2px 0;
        }
    </style>
    <div class="mdl-grid">

        <div class="mdl-shadow--4dp mdl-cell mdl-cell--8-col">
            <form method="post" id="data">
                {% csrf_token %}


                <div class="mdl-grid ">

                    <div id="div_id_patient_no"
                         class="hidden mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--4-col">
                        <label for="id_patient_no" class="mdl-textfield__label mdl-color-text--black">
                            Patient id</label>
                        <div class="controls"><input class="mdl-textfield__input" cols="40" id="id_patient_no"
                                                     maxlength="100" name="patient_no" value="{% if patient.patient_no != None %}{{ patient.patient_no }}{% endif %}" rows="10"
                                                     readonly>
                        </div>
                    </div>

                    <div id="div_id_patient_name"
                         class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--4-col">
                        <label for="id_patient_name" class="mdl-textfield__label mdl-color-text--black">
                            Patient Name</label>
                        <div class="controls"><input class="mdl-textfield__input" cols="30" id="id_patient_name"
                                                     maxlength="100" name="patient_name" value="{% if patient.patient_name != None %}{{ patient.patient_name }}{% endif %}" rows="10"
                                                     readonly></div>
                    </div>

                    <div class="phone mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--4-col">
                        <label class="mdl-textfield__label mdl-color-text--grey"
                               for="textfield_phone_number">Phone </label>
                        <input class="mdl-textfield__input" type='tel'
                               id="textfield_phone_number" value="{% if form.phone_number.value != None %}{{ form.phone_number.value }}{% else %}{% if patient.phone != None %}{{ patient.phone }}{% endif %}{% endif %}"
                               name="phone_number"/>
                    </div>
                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--4-col">
                        <label class="mdl-textfield__label mdl-color-text--grey"
                               for="textfield_email">Email Address</label>
                        <input class="mdl-textfield__input" type="email"
                               id="textfield_email"
                               value="{% if form.email.value != None %}{{ form.email.value }}{% else %}{% if patient.email != None %}{{ patient.email }}{% endif %}{% endif %}"
                               name="email" required/>
                    </div>

                    <script>
                        $('.phone').addClass('is-dirty')

                        $('#textfield_phone_number').on('keyup', function (e) {
                            $('.phone').addClass('is-dirty')
                            var number = $("#textfield_phone_number").intlTelInput("getNumber");
                            $("#textfield_phone_number").val(number)

                        });


                        $("#textfield_phone_number").intlTelInput();

                    </script>

                </div>
                <div class="mdl-grid ">
                    <div id="div_id_address"
                         class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--8-col">
                        <label for="id_address" class="mdl-textfield__label mdl-color-text--grey">
                            Physical Address</label>
                            <textarea class="mdl-textfield__input" cols="40" id="id_address"
                                      maxlength="400" name="address" rows="4"
                                      required="">{% if form.address.value != None %}{{ form.address.value }}{% else %}{{ patient.postal_address|default_if_none:"" }}{% endif %}</textarea>
                    </div>
                </div>
                <div class="mdl-grid">
                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--8-col">
                        <label for="id_delivery_address" class="mdl-textfield__label mdl-color-text--grey">
                            Delivery Address</label>
                        <input class="mdl-textfield__input" cols="40" onfocus="this.placeholder = ''"
                               onblur="this.placeholder = 'Enter the medicine you want to search'"
                               id="delivery_address" maxlength="100" name="delivery_address" rows="10"
                               placeholder="Enter Your Delivery Address" />
                    </div>
                </div>
                <div class="mdl-grid ">
                    <div class="mdl-cell mdl-cell--12-col">
                        <div id="div_id_prescription"
                             class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--12-col" >
                            <label for="id_prescription" class="mdl-textfield__label mdl-color-text--grey">
                                Prescription </label>
                            <div id="prescription_tags"></div>
                            <div class="controls">
                                <input class="mdl-textfield__input" cols="40" onfocus="this.placeholder = ''"
                                       onblur="this.placeholder = 'Enter the medicine you want to search'"
                                       id="medicationlist" maxlength="100" name="medicationlist" rows="10"
                                       placeholder="Enter the medicine you want to search"
                                       onkeyup="getsearch(this.value)"/>
                            <textarea class="hidden mdl-textfield__input" cols="40" id="id_prescription" maxlength="400"
                                      name="prescription" rows="10"
                                      required="">{{ form.prescription.value|default_if_none:"" }}</textarea></div>
                        </div>


                        <div id="no_result" class="search" style="display: none">
                            <div class="mdl-card__title mdl-card--expand results">
                                <h2 class="mdl-card__title-text">No Results</h2>
                            </div>
                        </div>
                        <div id="searchresult" class="search full-width "
                             style="display: none; height: 300px; overflow-x: auto; overflow-y: auto; margin-top: -20px">
                            <table id="search_table" class="mdl-data-table mdl-js-data-table results full-width ">
                                <thead>
                                <tr>
                                    <th class="mdl-data-table__cell--non-numeric full-width">Brand Name</th>
                                </tr>
                                </thead>
                                <tbody id="livesearch">
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

                <div id="prescriptionlist">
                </div>
                <div class="mdl-grid">
                    <button class="mdl-button mdl-js-ripple-effect mdl-js-button mdl-button--raised mdl-button--colored mdl-color--primary"
                            type="submit">Submit
                    </button>
                    &nbsp;
                    <button class="mdl-button mdl-js-ripple-effect mdl-js-button mdl-button--raised mdl-button--colored mdl-color--primary"
                            type="button" id="sendemail">Send Prescription
                    </button>

                </div>
                <div class="mdl-grid">

                </div>

            </form>
        </div>


        <div class="prescard mdl-cell mdl-cell--4-col">
            <h2 class="mdl-card__title-text" style="font-size:16px; padding:20px; border-bottom:1px solid #ccc; ">
                Previous Prescriptions</h2>
            <div class="mdl-card__title" id="myprescription" style="font-size:12px; color: #6b6666; padding:20px; ">
            </div>

        </div>

        <div class="mdl-layout-spacer"></div>
    </div>
    <script type="text/javascript">

    </script>
{% endblock %}

medication/templates/medication/medication_list.html
{% extends "base.html" %} {% load static %} {% block content %}
<script>
    $("#prescription_tab").addClass("current").siblings().removeClass("current")
</script>
<table class="table">
    <tr>
        <td>ID</td>
        <td>Link</td>
        <td>slug</td>
        <td>created</td>
        <td>last_updated</td>
        <td>prescription_id</td>
        <td>patient_no</td>
        <td>patient_name</td>
        <td>address</td>
        <td>phone_number</td>
        <td>signature</td>
        <td>prescription</td>
    </tr>
    {% for object in object_list %}
    <tr>
        <td>{{object.pk}}</td>
        <td><a href="{{object.get_absolute_url}}">{{object}}</a></td>
        <td>{{ object.slug }}</td>
        <td>{{ object.created }}</td>
        <td>{{ object.last_updated }}</td>
        <td>{{ object.prescription_id }}</td>
        <td>{{ object.patient_no }}</td>
        <td>{{ object.patient_name }}</td>
        <td>{{ object.address }}</td>
        <td>{{ object.phone_number }}</td>
        <td>{{ object.signature }}</td>
        <td>{{ object.prescription }}</td>
    </tr>
    {% endfor %}
</table>{% endblock %}

medication/templates/medication/medication_search.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <script>
    $("#prescription_tab").addClass("current").siblings().removeClass("current")
</script>

    <div class="mdl-grid ">
    <div class="mdl-layout-spacer"></div>

        <div class="mdl-card mdl-shadow--16dp util-center mdl-cell mdl-cell--12-col">
            <style>
                .mdl-card__title-text {
                    display: flex;
                    box-sizing: border-box;
                    align-items: center;
                }
            </style>
            <div class="mdl-card__title mdl-color--teal-500 ">
                <h2 class="mdl-card__title-text mdl-color-text--white" style="justify-content: center">Search Patient</h2>
            </div>

            <div class="mdl-grid" id="search_members">
                <!-- Wide card with share menu button -->
                <style>
                    .demo-card-wide.mdl-card {
                        width: 512px;
                    }

                    .demo-card-wide > .mdl-card__title {
                        color: #fff;
                        height: 176px;
                    {#            background: url('../assets/demos/welcome_card.jpg') center / cover;#}
                    }

                    .demo-card-wide > .mdl-card__menu {
                        color: #fff;
                    }
                </style>

                <div class="demo-card-wide mdl-card mdl-shadow--2dp">
                    <!-- Search -->
                    <style>
                        /* TODO: Hover and Focus state.
            *       Fix position of mobile search button.
            */
                        .mdh-expandable-search {
                            margin: 0 50px;
                            align-items: center;
                            justify-content: center;
                        }

                        .mdh-expandable-search form {
                            max-width: 600px;
                        }

                        .mdh-expandable-search,
                        .mdh-expandable-search form,
                        .mdh-expandable-search input {
                            /* Cross browser flex-grow */
                            -webkit-box-flex: 1;
                            -webkit-flex-grow: 1;
                            -ms-flex-positive: 1;
                            flex-grow: 1;
                        }

                        .mdh-expandable-search,
                        .mdh-expandable-search form {
                            /* Cross browser inline-flex */
                            display: -webkit-inline-box;
                            display: -webkit-inline-flex;
                            display: -moz-inline-box;
                            display: -ms-inline-flexbox;
                            display: inline-flex;
                        }

                        /* Position search icon */
                        .mdh-expandable-search .material-icons {
                            position: relative;
                            right: -40px;
                            margin-left: -24px; /* Remove the blank space left behind by the icon being relatively positioned */
                        }

                        .mdh-expandable-search input {
                            outline: none;
                            border: none;
                            font-size: 16px;
                            color: #FFFFFF;
                            background-color: #78909C;
                            padding: 0px 35px 0px 70px;
                            height: 40px;
                            line-height: 40px; /* TODO: This was recommended for cross browser compatability of input height, check if its actually needed in modern browsers */

                            border-radius: 5px 5px 5px 5px;
                            -moz-border-radius: 5px 5px 5px 5px;
                            -webkit-border-radius: 5px 5px 5px 5px;
                        }

                        .mdh-expandable-search input::-webkit-input-placeholder { /* WebKit browsers */
                            color: #FFFFFF;
                        }

                        .mdh-expandable-search input:-moz-placeholder { /* Mozilla Firefox 4 to 18 */
                            color: #FFFFFF;
                            opacity: 1; /* Firefox gives the placeholder a reduced opacity so we have to increase it */
                        }

                        .mdh-expandable-search input::-moz-placeholder { /* Mozilla Firefox 19+ */
                            color: #FFFFFF;
                            opacity: 1; /* Firefox gives the placeholder a reduced opacity so we have to increase it */
                        }

                        .mdh-expandable-search input:-ms-input-placeholder { /* Internet Explorer 10+ */
                            color: #FFFFFF;
                        }

                        /* Bug fix: https://github.com/google/material-design-lite/issues/1078
                         * To much padding on the left of header when the menu button is hidden */
                        @media screen and (min-width: 851px) {
                            .mdl-layout__header-row {
                                padding: 0 40px 0 40px;
                            }
                        }

                        /* Bug fix for badges being in the wrong location */
                        .mdl-badge[data-badge]:after {
                            right: -7px;
                            top: -8px;
                        }
                    </style>

                    {#                    preauth scrips#}
                    <script>
                        //       hide the two icons if the search box is below a certain size.
                        $(document).ready(function () {


                            $('.mdh-toggle-search').click(function () {
                                // No search bar is currently shown
                                if ($(this).find('i').text() == 'search') {
                                    $(this).find('i').text('cancel');
                                    $(this).removeClass('mdl-cell--hide-tablet mdl-cell--hide-desktop'); // Ensures the close button doesn't disappear if the screen is resized.

                                    $('.mdl-layout__drawer-button, .mdl-layout-title, .mdl-badge, .mdl-layout-spacer').hide();
                                    $('.mdl-layout__header-row').css('padding-left', '16px'); // Remove margin that used to hold the menu button
                                    $('.mdh-expandable-search').removeClass('mdl-cell--hide-phone').css('margin', '0 16px 0 0');

                                }
                                // Search bar is currently showing
                                else {
                                    $(this).find('i').text('search');
                                    $(this).addClass('mdl-cell--hide-tablet mdl-cell--hide-desktop');

                                    $('.mdl-layout__drawer-button, .mdl-layout-title, .mdl-badge, .mdl-layout-spacer').show();
                                    $('.mdl-layout__header-row').css('padding-left', '');
                                    $('.mdh-expandable-search').addClass('mdl-cell--hide-phone').css('margin', '0 50px');
                                }

                            });


                        });



                        //Do ajax call for search box
                         function searchMembers(str) {

                        //string must not be empty or less than two characters
                        if (/\S/.test(str) && str.length > 1) {
                            $.ajax({
                                url: "/registration/api/v1/patients/",
                                type: "get",
                                data: {

                                    search: str,
                                },
                                success: function(json) {
                                    console.log(json)
                                    if (json.length === 0) {
                                        $("#no_result").show()
                                        $('#searchresult').hide()

                                    } else {

                                        $("#no_result").hide()
                                        $('#searchresult').show()

                                        //ensure to remove previous prepended results to avoid duplicity
                                        $('#search_table tbody').children().remove();

                                        var tbody = $('#search_table tbody'),
                                            props = ["patient_no", "first_name", "last_name", "ss_number", "dob"]
                                        $.each(json, function(i, reservation) {
                                            var tr = $("<tr onclick=\"window.location.href='/medication/medication/new/" + json[i].patient_no + "/'\">");
                                            $.each(props, function(i, prop) {
                                                $('<td class="mdl-data-table__cell--non-numeric">').html(reservation[prop]).appendTo(tr);
                                            });
                                            tbody.append(tr);
                                        });

                                    }

                                }

                            })
                        } else {

                            $("#no_result").hide()
                            $('#searchresult').hide()

                        }
                    }

                        
                    </script>

                    <div class="mdh-expandable-search mdl-cell--hide-phone">
                        <i class="material-icons">search</i>
                            <input type="text" id="search" placeholder="Search" size="1"
                                   onkeyup="searchMembers(this.value)">
                    </div>


                    <div id="no_result" style="display: none">
                        <div class="mdl-card__title mdl-card--expand">
                            <h2 class="mdl-card__title-text">No Results</h2>
                        </div>
                    </div>

                    <div id="searchresult" style="display: none">
                        <table id="search_table" class="mdl-data-table mdl-js-data-table ">
                            <thead>
                            <tr>
                                <th class="mdl-data-table__cell--non-numeric full-width">Patient No</th>
                                <th>First Name</th>
                                <th>Last Name</th>
                                <th>ID No.</th>
                                <th>Date of Birth</th>
                            </tr>
                            </thead>
                            <tbody>

                            </tbody>
                        </table>
                    </div>
                </div>

            </div>


        </div>
    <div class="mdl-layout-spacer"></div>
    </div>


{% endblock %}

medication/templates/medication/prescription_print.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>







</body>
</html>